export const FUNCTION_WORDS = new Map([
	['a', 'first_mention_article'],
	['an', 'first_mention_article'],
	['certainly', 'emphatic_affirmative_polarity'],
	['could', 'conditional_could'],
	['definitely', 'definite_mood'],
	['extremely', 'extremely_intensified_degree'],
	['least', 'least_degree'],
	['might', 'might_mood'],
	['must', 'must_mood'],
	['not', 'negative_polarity'],
	['of', 'genitive'],
	['probably', 'probable_mood'],
	['should', 'should_mood'],
	['stop', 'cessative_aspect'],
	['stopped', 'cessative_aspect|past_time'],
	['stops', 'cessative_aspect|present_time'],
	['than', 'comparative_degree'],
	['that', 'singular_distal|relativizer|complementizer'],
	['the', 'routine_article'],
	['these', 'plural_proximal'],
	['this', 'singular_proximal'],
	['those', 'plural_distal'],
	['to', 'destination|infinitive'],
	['too', 'too_degree'],
	['very', 'intensified_degree'],
	['will', 'future_time'],
	['would', 'conditional_would'],
	['who', 'interrogative_person|relativizer'],
	['whom', 'relativizer'],
	['what', 'interrogative_thing|relativizer'],
	['which', 'interrogative_which'],
])

