# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB_Ontology" # i.e. available in your Worker on env.DB
database_name = "Ontology.2023-12-07.3_0_9485"
database_id = "82a4e9d7-74a8-4d4d-80d9-1ced55a77d44"

[[d1_databases]]
binding = "DB_Editor" # i.e. available in your Worker on env.DB
database_name = "Editor.2024-01-17"
database_id = "9e41f5db-4bc0-4903-82a0-9318c91d533c"
