# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "Editor.2024-03-07"
database_id = "1cafb9bd-be9b-4c3c-a4d0-ac0394126cd6"