# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "Editor.2024-03-01"
database_id = "259e4056-4a21-407f-a686-63066bb65fdd"
